# Generated by Django 5.2.6 on 2025-09-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('nuomininkas', 'Nuomininkas'), ('nuomotojas', 'Nuomotojas')], default='nuomininkas', max_length=12),
        ),
    ]
