# Generated by Django 5.2.6 on 2025-09-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0002_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='residence_declaration_allowed',
            field=models.BooleanField(default=False, verbose_name='Leidžiama deklaruoti gyvenamąją vietą'),
        ),
    ]
