# Generated by Django 5.2.6 on 2025-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0003_property_residence_declaration_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('nuomininkas', 'Nuomininkas'), ('nuomotojas', 'Nuomotojas')], default=None, max_length=12, null=True),
        ),
    ]
