# Generated by Django 5.2.6 on 2025-09-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0005_supportticket_supportticketupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_listing_enabled', models.BooleanField(default=False, verbose_name='Įjungti mokamus skelbimus')),
                ('listing_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Skelbimo aktyvavimo kaina')),
            ],
            options={
                'verbose_name_plural': 'Sistemos nustatymai',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='is_paid_listing',
            field=models.BooleanField(default=False, verbose_name='Apmokėtas skelbimas'),
        ),
    ]
