# Generated by Django 5.2.6 on 2025-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0006_systemsettings_property_is_paid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='house_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
