# Generated by Django 5.2.6 on 2025-09-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0007_property_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='flat_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Buto numeris'),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_number',
            field=models.CharField(max_length=20),
        ),
    ]
