# Generated by Django 5.2.6 on 2025-09-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0008_property_flat_number_alter_property_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apmokėjimo data'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('paruostas', 'Paruoštas nuomai'), ('remontas', 'Atliekamas remontas'), ('isnuomotas', 'Išnuomotas'), ('nepasiekiamas', 'Nepasiekiamas'), ('nuoma_pasibaigusi', 'Pasibaigusi nuoma')], max_length=20),
        ),
    ]
