# Generated by Django 5.2.6 on 2025-11-16 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0009_property_paid_at_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Neapmokėta'), ('pending', 'Laukiama patvirtinimo'), ('paid', 'Apmokėta')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Norima nuomos pradžia'),
        ),
    ]
