# Generated by Django 4.2.26 on 2025-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomoklis_app", "0010_invoice_status_alter_rentalrequest_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="period_date",
            field=models.DateField(
                blank=True,
                help_text="Mėnuo, už kurį išrašyta sąskaita (visada 1-a diena)",
                null=True,
            ),
        ),
    ]
