# Generated by Django 4.2.26 on 2025-11-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nomoklis_app", "0011_invoice_period_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemreport",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="problem_reports",
                to="nomoklis_app.invoice",
                verbose_name="Sąskaita",
            ),
        ),
    ]
