# Generated by Django 5.2.6 on 2025-11-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0012_problemreport_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tik nuomos suma, be depozito, remonto ir komunalinių', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('nuomotojas', 'Nuomotojas'), ('nuomininkas', 'Nuomininkas')], max_length=11, null=True, verbose_name='Kas apmoka?'),
        ),
    ]
