# Generated by Django 5.2.6 on 2025-11-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0013_invoice_rent_amount_alter_problemreport_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='activation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sumokėta už aktyvavimą'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='listing_price_tier_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Skelbimo aktyvavimo kaina (3-4 objektai)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='listing_price_tier_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Skelbimo aktyvavimo kaina (5+ objektai)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='listing_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Skelbimo aktyvavimo kaina (1-2 objektai)'),
        ),
    ]
