# Generated by Django 5.2.6 on 2025-11-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0014_property_activation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='listing_percentage_tier_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Procentas (1-2 objektai)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='listing_percentage_tier_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Procentas (3-4 objektai)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='listing_percentage_tier_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Procentas (5+ objektai)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='pricing_model',
            field=models.CharField(choices=[('fixed', 'Fiksuota kaina'), ('percentage', 'Procentas nuo nuomos kainos')], default='fixed', max_length=20, verbose_name='Kainodaros modelis'),
        ),
    ]
