# Generated by Django 5.2.6 on 2025-11-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0015_systemsettings_listing_percentage_tier_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='pricing_model',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_fixed_pricing',
            field=models.BooleanField(default=True, verbose_name='Įjungti fiksuotą kainodarą'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_percentage_pricing',
            field=models.BooleanField(default=False, verbose_name='Įjungti procentinę kainodarą'),
        ),
    ]
