# Generated by Django 5.2.6 on 2025-11-24 14:16

import nomoklis_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoklis_app', '0017_property_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/', validators=[nomoklis_app.validators.validate_image_extension, nomoklis_app.validators.validate_file_size], verbose_name='Profilio nuotrauka'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/', validators=[nomoklis_app.validators.validate_image_extension, nomoklis_app.validators.validate_file_size]),
        ),
    ]
