from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # path('logout/', logout_view, name='logout'),
    path("", views.index, name="index"),
    # path("register/", views.register, name="register"),
    path("dashboard/", views.dashboard_redirect, name="dashboard_redirect"),
    path("dashboard/nuomotojas/", views.nuomotojas_dashboard, name="nuomotojas_dashboard"),
    path("dashboard/nuomininkas/", views.nuomininkas_dashboard, name="nuomininkas_dashboard"),
    path("add_property/", views.add_property, name="add_property"),
    path("edit_property/<int:property_id>/", views.edit_property_view, name="edit_property"),
    path("delete_property/<int:property_id>/", views.delete_property_view, name="delete_property"),
    path("my_properties/", views.my_properties_view, name="my_properties"),
    path("assign_tenant/<int:property_id>/", views.assign_tenant_view, name="assign_tenant"),
    path("confirm_lease/<int:lease_id>/", views.confirm_lease, name="confirm_lease"),
    path("reject_lease/<int:lease_id>/", views.reject_lease, name="reject_lease"),
    path("dashboard/stats/", views.stats_view, name="stats"),
    path('chat/<int:user_id>/', views.start_chat_view, name='start_chat'),
    path('chat/landlord/', views.landlord_chat_list, name='landlord_chat_list'),
    path('chat/tenant/', views.tenant_chat_list, name='tenant_chat_list'),
    path('chat/room/<str:room_name>/', views.chat_room_view, name='chat_room'),
    path('search/', views.property_search_view, name='property_search'),
    
    path('property/<int:property_id>/', views.property_detail_view, name='property_detail_view'),
    
    path('terminate_lease/<int:lease_id>/', views.terminate_lease_view, name='terminate_lease'),
    path('add_review/<int:lease_id>/', views.add_property_review_view, name='add_property_review'),
    path('submit_request/<int:property_id>/', views.submit_rental_request_view, name='submit_rental_request'),
    path('property/<int:property_id>/reviews/', views.property_reviews_view, name='property_reviews'),
    path('landlord/<int:landlord_id>/reviews/', views.landlord_reviews_view, name='landlord_reviews'),
    path('tenant/<int:tenant_id>/reviews/', views.tenant_reviews_view, name='tenant_reviews'),
    path('my_requests/', views.tenant_requests_view, name='tenant_requests'),
    path('reject_request/<int:request_id>/', views.reject_rental_request_view, name='reject_rental_request'),
    path('delete_request/<int:request_id>/', views.delete_rental_request_view, name='delete_rental_request'),
    path('profile/landlord/', views.landlord_profile_view, name='landlord_profile'),
    path('profile/landlord/edit/', views.landlord_profile_edit_view, name='landlord_profile_edit'),
    path('profile/tenant/', views.tenant_profile_view, name='tenant_profile'),
    path('profile/tenant/edit/', views.tenant_profile_edit_view, name='tenant_profile_edit'),
    path('landlord_preview/<int:landlord_id>/', views.landlord_preview_popup, name='landlord_preview'),
    path('report_problem/', views.report_problem_view, name='report_problem'),
    path('problems/', views.problem_list_view, name='problem_list'),
    path('landlord/problems/', views.landlord_problem_list_view, name='landlord_problem_list'),
    path('landlord/problems/<str:encrypted_id>/', views.landlord_problem_detail_view, name='landlord_problem_detail'),
    path('problems/<str:encrypted_id>/', views.tenant_problem_detail_view, name='tenant_problem_detail'),
    path('notifications/', views.notification_list_view, name='notification_list'),
    path('notifications/read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_as_read, name='mark_all_notifications_as_read'),
    path('notifications/popup/', views.notifications_popup_view, name='notifications_popup'),
    path('toggle_save/<int:property_id>/', views.toggle_save_property, name='toggle_save_property'),
    path('saved_properties/', views.saved_properties_view, name='saved_properties'),
    path('tenant_terminate_lease/<int:lease_id>/', views.tenant_terminate_lease_view, name='tenant_terminate_lease'),
    path('lease/<int:lease_id>/sign/', views.view_and_sign_contract, name='view_and_sign_contract'),
    path('request/<int:request_id>/prepare-contract/', views.prepare_and_edit_contract_view, name='prepare_and_edit_contract'),
    path('lease/<int:lease_id>/generate-invoice/', views.generate_invoice_view, name='generate_invoice'),
    path('lease/<int:lease_id>/invoices/', views.lease_invoices_view, name='lease_invoices'),
    path('request/<int:request_id>/popup/', views.rental_request_popup_view, name='rental_request_popup'),
    path('contracts/', views.landlord_contracts_page, name='contracts'),
    path('dashboard/profile/', views.profile_redirect_view, name='profile_redirect'),
    # path('login/', auth_views.LoginView.as_view(template_name='nomoklis_app/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(next_page='index'), name='logout'),
    path('my_requests/<int:request_id>/popup/', views.tenant_request_popup_view, name='tenant_request_popup'),
    path('my_requests/<int:request_id>/cancel/', views.cancel_rental_request_view, name='cancel_rental_request'),
    path('lease/<int:lease_id>/submit-readings/', views.submit_meter_readings_view, name='submit_meter_readings'),
    path('lease/<int:lease_id>/readings-popup/', views.latest_readings_popup_view, name='latest_readings_popup'),
    path('lease/<int:lease_id>/prepare-invoice-popup/', views.prepare_invoice_popup_view, name='prepare_invoice_popup'),
    path('invoice/<int:invoice_id>/delete/', views.delete_invoice_view, name='delete_invoice'),
    path('my-archive/', views.tenant_lease_archive_view, name='tenant_lease_archive'),
    path('property/image/delete/<int:image_id>/', views.delete_property_image, name='delete_property_image'),
    path('panel/', views.admin_dashboard, name='admin_dashboard'),
    path('panel/users/', views.admin_users_list, name='admin_users_list'),
    path('api/property-locations/', views.property_locations_api, name='property_locations_api'),
    path('panel/properties/', views.admin_properties_list, name='admin_properties_list'),
    path('panel/properties/update-status/<int:property_id>/', views.admin_update_property_status, name='admin_update_property_status'),
    path('panel/properties/delete/<int:property_id>/', views.admin_delete_property, name='admin_delete_property'),
    path('panel/support-tickets/', views.admin_support_ticket_list_view, name='admin_support_ticket_list'),
    path('panel/support-tickets/<int:ticket_id>/', views.admin_support_ticket_detail_view, name='admin_support_ticket_detail'),
    path('panel/settings/', views.admin_system_settings_view, name='admin_system_settings'),
    path('invoice/<int:invoice_id>/mark-as-paid/', views.mark_invoice_as_paid, name='mark_invoice_as_paid'), # Ši eilutė atrodo pasikartojanti, bet palieku, kaip buvo
    path('invoice/<int:invoice_id>/tenant-confirm-payment/', views.tenant_confirm_payment, name='tenant_confirm_payment'),
    path('choose-role/', views.choose_role_view, name='choose_role'),
    path('profile/change-password/', views.change_password_view, name='change_password'),
    path('accounts/', include('allauth.urls')),
    path('pay/invoice/<int:invoice_id>/', views.create_checkout_session, name='create_checkout_session'), # Ši eilutė atrodo pasikartojanti, bet palieku, kaip buvo
    path('pay/activate-property/<int:property_id>/', views.activate_property_payment, name='activate_property_payment'),
    path('delete_account/', views.delete_account_view, name='delete_account'),
    path('payment/success/', views.payment_success_view, name='payment_success'),
    path('payment/cancel/', views.payment_cancel_view, name='payment_cancel'),
    path('stripe/webhook/', views.stripe_webhook_view, name='stripe_webhook'),
    path('support/', views.support_ticket_list_view, name='support_ticket_list'),
    path('support/create/', views.create_support_ticket_view, name='create_support_ticket'),
    path('support/<int:ticket_id>/', views.support_ticket_detail_view, name='support_ticket_detail'),
    # Pridedame trūkstamus statinių puslapių maršrutus
    path('nuomotojams/', views.for_landlords_view, name='for_landlords'),
    path('nuomininkams/', views.for_tenants_view, name='for_tenants'),
    path('pagalba/', views.help_center_view, name='help_center'),

    path('terms-and-conditions/', views.terms_and_conditions_view, name='terms_and_conditions'),
    path('privacy-policy/', views.privacy_policy_view, name='privacy_policy'),

    path('panel/statistics/', views.admin_detailed_stats, name='admin_detailed_stats'),
]